package com.debugfix.dto;

/**
 * A JUnit regression test generated by the LLM.
 *
 * @param relativePath path relative to the repository root (forward slashes)
 * @param content      full test file content
 */
public record GeneratedTest(String relativePath, String content) {}
